name: Deploy to Oracle VM

on:
  push:
    branches:
      - deploy-auto
      - main
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest
    environment: production
    steps:
      - name: Checkout repository
        uses: actions/checkout@v4

      - name: Prepare remote directory
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            mkdir -p "${{ secrets.DEPLOY_PATH }}"

      - name: Upload project to server (SCP)
        uses: appleboy/scp-action@v0.1.7
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          source: "."
          target: ${{ secrets.DEPLOY_PATH }}
          overwrite: true
          exclude: |
            .git/**
            node_modules/**
            certbot/conf/**

      - name: Run restart script remotely
        uses: appleboy/ssh-action@v1.0.0
        with:
          host: ${{ secrets.SSH_HOST }}
          username: ${{ secrets.SSH_USER }}
          key: ${{ secrets.SSH_PRIVATE_KEY }}
          script: |
            set -e
            cd "${{ secrets.DEPLOY_PATH }}"
            chmod +x scripts/restart.sh || true
            ./scripts/restart.sh --no-cache
